# Generated by Django 6.0.2 on 2026-05-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_phone_number'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shops',
            field=models.ManyToManyField(blank=True, related_name='sellers', to='shops.shop', verbose_name='Магазины продавца'),
        ),
    ]
