# Generated by Django 5.2 on 2026-05-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_name_ky_category_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ky',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, unique=True),
        ),
    ]
