"""
Django settings for marketplace_config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import environ

# Initialize environ
env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Use environment variables
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])







# Application definition

INSTALLED_APPS = [
    # admin panel theme
    'jazzmin',
    'modeltranslation',


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'accounts.apps.AccountsConfig',
    'dashboard.apps.DashboardConfig',  # Дашборд приложения
    'orders.apps.OrdersConfig',  # Заказы приложения
    'products.apps.ProductsConfig',  # Товары приложения
    'categories.apps.CategoriesConfig',  # Категории приложения
    'cart.apps.CartConfig',  # Корзина приложения
    'shops.apps.ShopsConfig',  # Магазины приложения
    'favorites.apps.FavoritesConfig',  # Избранные товары приложения
    'analytics.apps.AnalyticsConfig',  # Бизнес-аналитика приложения
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Для обслуживания статических файлов в продакшене
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketplace_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Биздин жаңы контекст процессор:
                'categories.context_processors.menu_categories',
                
                # Бул контекст процессор ар бир шаблонго 'favorite_count' деген өзгөрмөнү кошот, ал колдонуучунун канча товарды сүйүктүү катары белгилегенин көрсөтөт
                'favorites.context_processors.favorite_count',

                # Биздин жаңы себет эсептегичибиз кошулду:
                'cart.context_processors.cart_counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL')
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:home'
LOGOUT_REDIRECT_URL = 'accounts:login'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = '/static/'
# Статикалык файлдарды чогулта турган папканын жолу
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Добавьте этот параметр для корректной работы
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Django статикалык файлдарды кайсы жерден издеши керек экенин так көрсөтөбүз:
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


"""
# Django 3.2ден баштап, жаңы долбоорлор үчүн DEFAULT_AUTO_FIELD параметри 
# 'django.db.models.BigAutoField' болуп өзгөртүлдү. 
# Бул автоматтык түрдө чоң автоинкременттик талааларды колдонууга мүмкүндүк берет,
#  бирок эгер сиз мурунку версиялар менен шайкештикти сактап калгыңыз келсе, 
#  аны 'django.db.models.AutoField' деп өзгөртө аласыз.
"""
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# 2. Языки
LANGUAGES = [
    ('ky', 'Кыргызча'),
    ('ru', 'Русский'),
]

# 3. Папка локалей
LOCALE_PATHS = [BASE_DIR / 'locale']