# Generated by Django 6.0.2 on 2026-05-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('delivering', 'Передан курьеру'), ('on_the_way', 'На маршруте'), ('delivered', 'Доставлен')], default='new', max_length=20),
        ),
    ]
