# Generated by Django 6.0.2 on 2026-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_address_order_comment_order_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена закупки на момент заказа'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена продажи на момент заказа'),
        ),
    ]
