# Generated by Django 6.0.2 on 2026-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_discount_percent_product_old_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена закупки'),
        ),
    ]
