# Generated by Django 6.0.2 on 2026-05-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
